version: '3'

services:
  producer:
    build: './Producer'
    restart: unless-stopped
    env_file:
      - docker.env
    volumes:
      - ./Producer:/opt/app/Producer
    depends_on:
      - redis
    ports:
      - 3000:3000

  consumer:
    build: './Consumer'
    restart: unless-stopped
    env_file:
      - docker.env
    volumes:
      - ./Consumer:/opt/app/Consumer
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
